workdir<-getwd()
workdir1<-paste(c(workdir,"/UCI HAR Dataset/test/X_test.txt"),collapse='')
workdir2<-paste(c(workdir,"/UCI HAR Dataset/test/y_test.txt"),collapse='')
workdir3<-paste(c(workdir,"/UCI HAR Dataset/test/subject_test.txt"),collapse='')
testx<-read.table(workdir1,header=FALSE)
testy<-read.table(workdir2,header=FALSE)
testsub<-read.table(workdir3,header=FALSE)
test<-cbind(testsub,testy,testx)
workdir4<-paste(c(workdir,"/UCI HAR Dataset/train/X_train.txt"),collapse='')
workdir5<-paste(c(workdir,"/UCI HAR Dataset/train/y_train.txt"),collapse='')
workdir6<-paste(c(workdir,"/UCI HAR Dataset/train/subject_train.txt"),collapse='')
workdir7<-paste(c(workdir,"/UCI HAR Dataset/activity_labels.txt"),collapse='')
workdir8<-paste(c(workdir,"/UCI HAR Dataset/features.txt"),collapse='')
trainx<-read.table(workdir4,header=FALSE)
trainy<-read.table(workdir5,header=FALSE)
trainsub<-read.table(workdir6,header=FALSE)
activity_lab<-read.table(workdir7,header=FALSE)
feature<-read.table(workdir8,header=FALSE,colClasses="character")
train<-cbind(trainsub,trainy,trainx)
bind<-rbind(test,train)
colnames(bind)[1:2]<-c("subject","activityid")
colnames(bind)[3:ncol(bind)]<-feature[,1]
index<-c(grep("mean\\(\\)",names(bind)),grep("std\\(\\)",names(bind)))
dataset<-bind[,c(1,2,index)]
colnames(activity_lab)<-c("activityid","activity")
library(dplyr)
data<-inner_join(activity_lab,dataset,by="activityid")
data<-data[,2:ncol(data)]
View(data %>% group_by(activity,subject) %>% summarise_each(funs(mean)))