workdir<-getwd()
workdir1<-paste(c(workdir,"/UCI HAR Dataset/test/X_test.txt"),collapse='')
workdir2<-paste(c(workdir,"/UCI HAR Dataset/test/y_test.txt"),collapse='')
workdir3<-paste(c(workdir,"/UCI HAR Dataset/test/subject_test.txt"),collapse='')
testx<-read.table(workdir1,header=FALSE)
testy<-read.table(workdir2,header=FALSE)
testsub<-read.table(workdir3,header=FALSE)
test<-cbind(testsub,testy,testx)
workdir1<-paste(c(workdir,"/UCI HAR Dataset/train/X_train.txt"),collapse='')
workdir2<-paste(c(workdir,"/UCI HAR Dataset/train/y_train.txt"),collapse='')
workdir3<-paste(c(workdir,"/UCI HAR Dataset/train/subject_train.txt"),collapse='')
trainx<-read.table(workdir1,header=FALSE)
trainy<-read.table(workdir2,header=FALSE)
trainsub<-read.table(workdir3,header=FALSE)
train<-cbind(trainsub,trainy,trainx)
bind<-rbind(test,train)
dataset<-bind[,c(1,2,3,4,5,6,7,8,43,44,45,46,47,48,83,84,85,86,87,88,123,124,125,126,127,128,163,164,165,166,167,168,203,204,216,217,229,230,242,243,255,256,268,269,270,271,272,273,347,348,349,350,351,352,426,427,428,429,430,431,505,506,518,519,531,532,544,545)]
colnames(dataset)<-c("subject","activityid","tBodyAcc-mean()-X",    "tBodyAcc-mean()-Y",	"tBodyAcc-mean()-Z",	"tBodyAcc-std()-X",	"tBodyAcc-std()-Y",	"tBodyAcc-std()-Z",	"tGravityAcc-mean()-X",	"tGravityAcc-mean()-Y",	"tGravityAcc-mean()-Z",	"tGravityAcc-std()-X",	"tGravityAcc-std()-Y",	"tGravityAcc-std()-Z",	"tBodyAccJerk-mean()-X",	"tBodyAccJerk-mean()-Y",	"tBodyAccJerk-mean()-Z",	"tBodyAccJerk-std()-X",	"tBodyAccJerk-std()-Y",	"tBodyAccJerk-std()-Z",	"tBodyGyro-mean()-X",	"tBodyGyro-mean()-Y",	"tBodyGyro-mean()-Z",	"tBodyGyro-std()-X",	"tBodyGyro-std()-Y",	"tBodyGyro-std()-Z",	"tBodyGyroJerk-mean()-X",	"tBodyGyroJerk-mean()-Y",	"tBodyGyroJerk-mean()-Z",	"tBodyGyroJerk-std()-X",	"tBodyGyroJerk-std()-Y",	"tBodyGyroJerk-std()-Z",	"tBodyAccMag-mean()",	"tBodyAccMag-std()",	"tGravityAccMag-mean()",	"tGravityAccMag-std()",	"tBodyAccJerkMag-mean()",	"tBodyAccJerkMag-std()",	"tBodyGyroMag-mean()",	"tBodyGyroMag-std()",	"tBodyGyroJerkMag-mean()",	"tBodyGyroJerkMag-std()",	"fBodyAcc-mean()-X",	"fBodyAcc-mean()-Y",	"fBodyAcc-mean()-Z",	"fBodyAcc-std()-X",	"fBodyAcc-std()-Y",	"fBodyAcc-std()-Z",	"fBodyAccJerk-mean()-X",	"fBodyAccJerk-mean()-Y",	"fBodyAccJerk-mean()-Z",	"fBodyAccJerk-std()-X",	"fBodyAccJerk-std()-Y",	"fBodyAccJerk-std()-Z",	"fBodyGyro-mean()-X",	"fBodyGyro-mean()-Y",	"fBodyGyro-mean()-Z",	"fBodyGyro-std()-X",	"fBodyGyro-std()-Y",	"fBodyGyro-std()-Z",	"fBodyAccMag-mean()",	"fBodyAccMag-std()",	"fBodyBodyAccJerkMag-mean()",	"fBodyBodyAccJerkMag-std()",	"fBodyBodyGyroMag-mean()",	"fBodyBodyGyroMag-std()",	"fBodyBodyGyroJerkMag-mean()",	"fBodyBodyGyroJerkMag-std()")
workdir4<-paste(c(workdir,"/UCI HAR Dataset/activity_labels.txt"),collapse='')
activity_lab<-read.table(workdir4,header=FALSE)
colnames(activity_lab)<-c("activityid","activity")
library(dplyr)
data<-inner_join(activity_lab,dataset,by="activityid")
data<-data[,2:69]
View(data %>% group_by(activity,subject) %>% summarise_each(funs(mean)))
data %>% group_by(activity,subject) %>% summarise_each(funs(mean))